### ISSUE TITLE
Responses in JSON are failing

### ISSUE THREAD

**Issue by Stuart-Wilcox** [Stuart-Wilcox/servepy#2]
Sending a response in JSON in endware results in an error being thrown. See the traceback:
```
Traceback (most recent call last)
    File "..\site-packages\servepy.py", line 34, in handle
        self.exec_callbacks(path, request.method, request, response)
    File "..\site-packages\servepy.py", line 140, in exec_callbacks
        callback(request, response)
    File "myServer.py", line 4, in MyMethod
        res.json('Hello')
    File "..\site-packages\servepy.py", line 645, in json
        self.headers['Content-Type'] = 'application/json'.upper()
AttributeError: 'Response' object has no attribute 'headers' 
```

The following simple method was invoked which caused the error:
```
# myServer.py

def MyMethod(req, res):
    res.json('Hello')
```

**Comment by Stuart-Wilcox** [comment]
This issue is patched with release 1.0.3
