### ISSUE TITLE
Sending an empty response causes an error

### ISSUE THREAD

**Issue by Stuart-Wilcox** [Stuart-Wilcox/servepy#4]
Using `res.send()` with no parameter causes the following error:
```
Traceback (most recent call last):
  File "../site-packages/servepy.py", line 39, in handle
    self.exec_callbacks(path, req, res)
  File "../site-packages/servepy.py", line 115, in exec_callbacks
    callback(request, response)
  File "server.py", line 27, in post_name
    res.send()
  File "../site-packages/servepy.py", line 707, in send
    self.set('Content-Length'.upper(), len(bytes(body, 'utf-8')))
TypeError: encoding without a string argument
``` 
It seems like the body can't be empty.

**Comment by Stuart-Wilcox** [comment]
This issue was resolved in release 1.0.3
